In [1]:
import numpy as np
import sys

# Basics

In [2]:
a=np.array([1,2,3,4,5,6])
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])

In [3]:
a.dtype

dtype('int32')

In [4]:
#get dimension
b.ndim

2

In [5]:
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [6]:
b.shape

(2, 3)

In [7]:
#get total size
a.nbytes

24

In [8]:
#Get number of elements
a.size

6

In [9]:
#get size
b.size

6

# Accessing/Changing specific elements, rows, columns, etc

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [11]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [12]:
#get specific element
a[1,5]

13

In [13]:
#get specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [14]:
#get specific column
a[:,4]

array([ 5, 12])

In [15]:
#[startindex:endindex:stepsize]
a[0,::-2]

array([7, 5, 3, 1])

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [17]:
b.shape

(2, 2, 2)

In [18]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
# Get specific element (work outside in)
b[1,1,1]

8

In [20]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

# Initializing Different Types of Arrays

In [21]:
 #all zero matrix
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
# all ones matrix
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
# all any number matrix
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [25]:
#takes the array to which it should be similar
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
#random decimal numbers
np.random.rand(4,2)

array([[0.99015053, 0.97349339],
       [0.90431982, 0.59901365],
       [0.51926688, 0.614887  ],
       [0.12738742, 0.40901189]])

In [27]:
np.random.random_sample(a.shape)

array([[0.73606228, 0.371221  , 0.37860841, 0.8018653 , 0.07358873,
        0.83777269, 0.82367859],
       [0.2183486 , 0.33552795, 0.98230998, 0.53639999, 0.49253627,
        0.44477417, 0.09348284]])

In [28]:
np.random.randint(10,size=(3,4))

array([[9, 1, 9, 1],
       [4, 1, 4, 1],
       [9, 1, 9, 4]])

In [29]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [30]:
#repeat an array
a1=np.array([[1,2,3]])
r1=np.repeat(a1,3,axis=0)

In [31]:
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [32]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [43]:
#use copy function to copy the values of arrays

# Mathematics

In [44]:
#element wise mathematics

In [33]:
a = np.array([1,2,3,4])

In [34]:
a+2

array([3, 4, 5, 6])

In [35]:
a-2

array([-1,  0,  1,  2])

In [36]:
a*2

array([2, 4, 6, 8])

In [37]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [38]:
b = np.array([1,0,1,0])

In [39]:
a+b

array([2, 2, 4, 4])

In [40]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [41]:
#take the trigno
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [42]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra

In [45]:
#matrix multiplication
a = np.ones((2,3))

b = np.full((3,2), 2)

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [49]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0],[7.0,8.0,1.0]])

In [51]:
#calculating the determinant
np.linalg.det(b)

23.999999999999982

In [52]:
np.linalg.eigvals(b)

array([18.7927891, -0.3734938, -3.4192953])

In [53]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Statistics

In [54]:
stats = np.array([[1,2,3],[4,5,6]])

In [55]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
stats.min()

1

In [57]:
stats.max()

6

In [58]:
np.max(stats, axis=1)

array([3, 6])

# Reorgnaizing Arrays

In [59]:
before = np.array([[1,2,3,4],[5,6,7,8]])

In [64]:
after=before.reshape(4,2)

In [62]:
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [66]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [68]:
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [69]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])